name: CI

on:
  push:
    branches: ["main"]
    tags: ['v*']
  pull_request:
  schedule:
    - cron: "34 6 * * 5"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-26.04, macos-latest]
        rust: [stable]
        include:
          - os: ubuntu-26.04
            rust: beta

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo check --all-targets
      - run: cargo check -p oxish --no-default-features --features aws-lc
      - run: cargo test --features graviola,aws-lc -- --include-ignored

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0
      # aws-lc-rs has a lower MSRV than graviola, so we use it to test our MSRV
      - run: cargo check -p oxish --no-default-features --features aws-lc --bins

  fips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check -p oxish --no-default-features --features aws-lc-fips

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      # use nightly to mirror docs.rs
      - uses: dtolnay/rust-toolchain@nightly
      - name: cargo doc
        run: cargo doc --locked --all-features --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: -Dwarnings

  coverage:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: cargo llvm-cov --workspace --lcov --output-path lcov.info -- --include-ignored
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: EmbarkStudios/cargo-deny-action@v2

  release:
    strategy:
      matrix:
        os: [ubuntu-26.04, macos-latest]
        rust: [stable]
        include:
          - os: ubuntu-26.04
            rust: beta

    runs-on: ${{ matrix.os }}

    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo build --release
      - name: Copy oxish-server-{{ matrix.os }} to output directory
        run: cp target/release/oxish-server output/oxish-server-{{ matrix.os }}
      - name: Copy oxish-session-{{ matrix.os }} to output directory
        run: cp target/release/oxish-session output/oxish-session-{{ matrix.os }}
      - name: Create the release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          working_directory: output
          files: |
            oxish-server-{{ matrix.os }}
            oxish-session-{{ matrix.os }}
